### PR TITLE
WIP: Add Education Seminar page

### PR DESCRIPTION
**Pull request by ncoghlan**

### CODE REVIEW

**Comment by ncoghlan** [comment]
@nickyringland @hogesonline Let me know if there's anything you'd like me to change about the Seminar or ACA descriptions before I remove the WIP marker from this :)

I'll also ask Nicola Curnow from Code Club Australia to take a look at their section.

**Comment by glasnt** [comment]
@ncoghlan let me know when you need a link from a main page and I'll make changes

**Comment by glasnt** [comment]
Hi @Bijesse, the CodeClub website says 75,000, which I believe is where we got that number from.

**Comment by Bijesse** [comment]
Hi @glasnt I just went back to double check and the numbers have been updated from data received by our 2017 census and, my apologies but the number of students served across Australia is actually 165,000. Some quick data points can be found on our homepage [codeclubau.org](https://codeclubau.org/)

**Comment by glasnt** [comment]
@Bijesse So would if I update that line to say "volunteers serving over 165,000 youth a week.", would that be accurate?

**Comment by Bijesse** [comment]
@glasnt That number is correct, however, the statement does not fully represent Code Club today. Nearly half of our clubs are now led by teachers and upon further thought, I would like to request the statement changes to reflect us more accurately. Would it be possible to update the section to the statement below:
 
Code Club is a network of clubs led by teachers and volunteers to get kids coding. Code Club offers over 100+ hours of digital technologies aligned projects and activities to bring coding to classrooms, libraries and community centres across the country. Currently, Code Club impacts more than 165,000 children a week across a network of 2,200+ clubs and schools. All for free. 

Code Club also offers Free certified training for teachers wanting to get across Digital Technologies for their school. Learn more at [codeclubau.org](http://codeclubau.org)

**Comment by glasnt** [comment]
Thanks @Bijesse. I've updated the page with your new wording.

**Pull request merged**
